### ISSUE TITLE
ValueError: Cannot create group in read-only mode.

### ISSUE THREAD

**Issue by vbqgyy** [pvitoria/ChromaGAN#11]
G:\proj\YUs_Ai\02PYTORCH\04color\ChromaGAN-master\MODEL/imagenet/modelPretrained.h5
Traceback (most recent call last):
  File "ChromaGANPrint.py", line 112, in <module>
    sample_images(not args.no_concatenate)
  File "ChromaGANPrint.py", line 58, in sample_images
    colorizationModel = load_model(save_path)
  File "G:\SUCAI\Anaconda3\envs\PY388\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "G:\SUCAI\Anaconda3\envs\PY388\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "G:\SUCAI\Anaconda3\envs\PY388\lib\site-packages\keras\engine\saving.py", line 270, in _deserialize_model
    model_config = h5dict['model_config']
  File "G:\SUCAI\Anaconda3\envs\PY388\lib\site-packages\keras\utils\io_utils.py", line 318, in __getitem__
    raise ValueError('Cannot create group in read-only mode.')
ValueError: Cannot create group in read-only mode.

win10
3090

**Comment by pvitoria** [comment]
Hi,
I hope you fix already this problem.
I never had this problem but here there is a possible solution:
https://stackoverflow.com/questions/53212672/read-only-mode-in-keras
